const purposes = [
  { name: "All", value: "" },
  { name: "Cycle", value: "Cycle" },
  { name: "Cycle ( 3 Wheels )", value: "Cycle ( 3 Wheels )" },
  { name: "Car", value: "Car" },
  { name: "Bus ( City )", value: "Bus ( City )" },
  { name: "Bus ( High Way )", value: "Bus ( High Way )" },
  { name: "Light Truck ( City )", value: "Light Truck ( City )" },
  { name: "Light Truck ( High way )", value: "Light Truck ( High way )" },
  { name: "Heavy Truck ( City )", value: "Heavy Truck ( City )" },
  { name: "Heavy Truck ( High way )", value: "Heavy Truck ( High way )" },
  { name: "Trailer ( City )", value: "Trailer ( City )" },
  { name: "Trailer ( High way )", value: "Trailer ( High way )" },
  { name: "Htawlargyi", value: "Htawlargyi" },
  { name: "Tractor", value: "Tractor" },
  { name: "Small Tractor", value: "Small Tractor" },
  { name: "Heavy Machinery", value: "Heavy Machinery" },
  { name: "Commercial Vehicle", value: "Commercial Vehicle" },
  { name: "Phone Tower", value: "Phone Tower" },
  { name: "Industrial Zone", value: "Industrial Zone" },
  { name: "Generator Industry", value: "Generator Industry" },
  { name: "Agriculture Machine", value: "Agriculture Machine" },
  { name: "Generator ( Home Use )", value: "Generator ( Home Use )" },
  { name: "Hospital", value: "Hospital" },
  { name: "School", value: "School" },
  { name: "Super Market", value: "Super Market" },
  { name: "Hotel", value: "Hotel" },
  { name: "Housing", value: "Housing" },
  { name: "Boat", value: "Boat" },
  { name: "Pump Test", value: "Pump Test" },
  { name: "Office Use ( Bowser Car )", value: "Office Use ( Bowser Car )" },
  { name: "Station Use", value: "Station Use" },
];
export default purposes;
